name: Build and deploy with Nikola
on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build and deploy website to gh-pages'
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Change sass binary in conf.py
      run: sed -i "s|SASS_COMPILER = 'sass'|SASS_COMPILER = 'sassc'|g" conf.py

    - name: Build the site with Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: true
        apt_install: sassc

    - name: Deploy to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./output/
        clean-exclude: previews/
