name: Build and deploy with Nikola
on:
  push:
    branches:
    - main

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build and deploy website to gh-pages'
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Change sass binary in conf.py
      run: sed -i "s|SASS_COMPILER = 'sass'|SASS_COMPILER = 'sassc'|g" conf.py

    - name: Deploy site (via Nikola action)
      uses: getnikola/nikola-action@v8
      with:
        dry_run: false
        apt_install: sassc
